preprocess:
    raw_data_file: experiments/10K_accts/data/raw/tx_log.csv
    preprocessed_data_dir: experiments/10K_accts/data/preprocessed
    num_windows: 4 
    window_len: 28
    train_start_step: 0
    train_end_step: 112
    val_start_step: 0
    val_end_step: 112
    test_start_step: 0
    test_end_step: 112
    include_edges: true

LogisticRegressor:
    default:
        client_type: TorchClient
        server_type: TorchServer
        device: cuda:0
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        lr_patience: 10
        es_patience: 300
        n_rounds: 300
        eval_every: 5
        n_warmup_rounds: 100
        batch_size: 512
        optimizer: Adam
        criterion: BCEWithLogitsLoss
        lr: 0.001
        input_dim: 94
        output_dim: 1
    centralized:
        trainset: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        lr: 0.005215764062323175
    federated:
        clients:
            c0:
                trainset: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
        lr: 0.009979119601807604
    isolated:
        clients:
            c0:
                trainset: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                lr: 0.008975242336657445
    search_space:
        lr:
            type: float
            low: 0.00001
            high: 0.01
            log: true

MLP:
    default:
        client_type: TorchClient
        server_type: TorchServer
        device: cuda:0
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        lr_patience: 10
        es_patience: 300
        n_rounds: 300
        eval_every: 5
        n_warmup_rounds: 100
        batch_size: 512
        optimizer: Adam
        criterion: BCEWithLogitsLoss
        lr: 0.001
        weight_decay: 0.1
        input_dim: 94
        n_hidden_layers: 3
        hidden_dim: 100
        output_dim: 1
    centralized:
        trainset: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        lr: 1.8532615226702213e-05
        weight_decay: 0.004386165139107806
        n_hidden_layers: 1
        hidden_dim: 294
    federated:
        clients:
            c0:
                trainset: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
        lr: 0.0017304319353381955
        weight_decay: 0.0005114530027638688
        n_hidden_layers: 1
        hidden_dim: 259
    isolated:
        clients:
            c0: 
                trainset: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                lr: 0.0005600950976239333
                weight_decay: 0.0025857677628087234
                n_hidden_layers: 1
                hidden_dim: 92
    search_space:
        lr:
            type: float
            low: 0.00001
            high: 0.01
            log: true
        weight_decay:
            type: float
            low: 0.0
            high: 1.0
        n_hidden_layers:
            type: int
            low: 1
            high: 5
        hidden_dim:
            type: int
            low: 50
            high: 300

GCN:
    default:
        client_type: TorchGeometricClient
        server_type: TorchServer
        device: cuda:0
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        lr_patience: 10
        es_patience: 300
        n_rounds: 300
        n_warmup_rounds: 100
        eval_every: 5
        optimizer: Adam
        criterion: BCEWithLogitsLoss
        lr: 0.0001
        dropout: 0.9
        input_dim: 94
        n_conv_layers: 3
        hidden_dim: 100
        output_dim: 1
    centralized:
        trainset_nodes: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        trainset_edges: experiments/10K_accts/data/preprocessed/centralized/trainset_edges.csv
        lr: 0.04985579806880382
        n_conv_layers: 2
        hidden_dim: 228
        dropout: 0.212518745917199
    federated:
        clients:
            c0:
                trainset_nodes: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                trainset_edges: experiments/10K_accts/data/preprocessed/clients/c0/trainset_edges.csv
        lr: 0.05428834813364031
        n_conv_layers: 1
        hidden_dim: 103
        dropout: 0.2029401732542072
    isolated:
        clients:
            c0:
                trainset_nodes: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                trainset_edges: experiments/10K_accts/data/preprocessed/clients/c0/trainset_edges.csv
                lr: 0.0002489009744571275
                n_conv_layers: 1
                hidden_dim: 206
                dropout: 0.5184838929429599
    search_space:
        lr:
            type: float
            low: 0.0001
            high: 0.1
            log: true
        n_conv_layers:
            type: int
            low: 1
            high: 5
        hidden_dim:
            type: int
            low: 100
            high: 300
        dropout:
            type: float
            low: 0.2
            high: 0.9

GAT:
    default:
        client_type: TorchGeometricClient
        server_type: TorchServer
        device: cuda:0
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        lr_patience: 10
        es_patience: 300
        n_rounds: 300
        n_warmup_rounds: 100
        eval_every: 5
        optimizer: Adam
        criterion: BCEWithLogitsLoss
        lr: 0.0001
        dropout: 0.9
        input_dim: 94
        n_conv_layers: 3
        hidden_dim: 100
        output_dim: 1
    centralized:
        trainset_nodes: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        trainset_edges: experiments/10K_accts/data/preprocessed/centralized/trainset_edges.csv
        lr: 0.011546159544637308
        n_conv_layers: 4
        hidden_dim: 272
        dropout: 0.3448849009620575
    federated:
        clients:
            c0:
                trainset_nodes: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                trainset_edges: experiments/10K_accts/data/preprocessed/clients/c0/trainset_edges.csv
        lr: 0.061710055608632526
        n_conv_layers: 1
        hidden_dim: 283
        dropout: 0.2912341611265082
    isolated:
        clients:
            c0:
                trainset_nodes: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                trainset_edges: experiments/10K_accts/data/preprocessed/clients/c0/trainset_edges.csv
                lr: 0.0008494710519022342
                n_conv_layers: 1
                hidden_dim: 246
                dropout: 0.23214982250924754
    search_space:
        lr:
            type: float
            low: 0.0001
            high: 0.1
            log: true
        n_conv_layers:
            type: int
            low: 1
            high: 5
        hidden_dim:
            type: int
            low: 100
            high: 300
        dropout:
            type: float
            low: 0.2
            high: 0.9

GraphSAGE:
    default:
        client_type: TorchGeometricClient
        server_type: TorchServer
        device: cuda:0
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        lr_patience: 10
        es_patience: 300
        n_rounds: 300
        n_warmup_rounds: 100
        eval_every: 5
        optimizer: Adam
        criterion: BCEWithLogitsLoss
        lr: 0.0001
        dropout: 0.9
        input_dim: 94
        n_conv_layers: 3
        hidden_dim: 100
        output_dim: 1
    centralized:
        trainset_nodes: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        trainset_edges: experiments/10K_accts/data/preprocessed/centralized/trainset_edges.csv
        lr: 0.00011079925591955156
        n_conv_layers: 5
        hidden_dim: 168
        dropout: 0.2075355287658825
    federated:
        clients:
            c0:
                trainset_nodes: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                trainset_edges: experiments/10K_accts/data/preprocessed/clients/c0/trainset_edges.csv
        lr: 0.0011139432921763851
        n_conv_layers: 1
        hidden_dim: 270
        dropout: 0.3632770341236877
    isolated:
        clients:
            c0:
                trainset_nodes: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                trainset_edges: experiments/10K_accts/data/preprocessed/clients/c0/trainset_edges.csv
                lr: 0.0001518982258454294
                n_conv_layers: 2
                hidden_dim: 191
                dropout: 0.2119595450512009
    search_space:
        lr:
            type: float
            low: 0.0001
            high: 0.1
            log: true
        n_conv_layers:
            type: int
            low: 1
            high: 5
        hidden_dim:
            type: int
            low: 100
            high: 300
        dropout:
            type: float
            low: 0.2
            high: 0.9

DecisionTreeClassifier:
    default:
        client_type: SklearnClient
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        criterion: gini
        splitter: best
        max_depth: ~
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: ~
        random_state: 42
        max_leaf_nodes: ~
        min_impurity_decrease: 0.0
        class_weight: balanced
        ccp_alpha: 0.0
        monotonic_cst: ~
    centralized:
        trainset: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        criterion: entropy
        splitter: random
        max_depth: 10
    isolated:
        clients:
            c0:
                trainset: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                criterion: gini
                splitter: best
                max_depth: 667
    search_space:
        criterion: 
            type: categorical
            values: [gini, entropy, log_loss]
        splitter: 
            type: categorical
            values: [best, random]
        max_depth:
            type: int
            low: 10
            high: 1000

RandomForestClassifier:
    default:
        client_type: SklearnClient
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        n_estimators: 100
        criterion: gini
        max_depth: ~
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_features: sqrt
        max_leaf_nodes: ~
        min_impurity_decrease: 0.0
        bootstrap: True
        oob_score: False
        n_jobs: ~
        random_state: 42
        verbose: 0
        warm_start: False
        class_weight: balanced
        ccp_alpha: 0.0
        max_samples: ~
        monotonic_cst: ~
    centralized:
        trainset: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        criterion: log_loss
        max_depth: 843
    isolated:
        clients:
            c0:
                trainset: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                criterion: log_loss
                max_depth: 843
    search_space:
        criterion: 
            type: categorical
            values: [gini, entropy, log_loss]
        max_depth:
            type: int
            low: 10
            high: 1000

GradientBoostingClassifier:
    default:
        client_type: SklearnClient
        # trainset_size: 0.1
        valset_size: 0.2
        testset_size: 0.2
        loss: log_loss
        learning_rate: 0.1
        n_estimators: 100
        subsample: 1.0
        criterion: friedman_mse
        min_samples_split: 2
        min_samples_leaf: 1
        min_weight_fraction_leaf: 0.0
        max_depth: 3
        min_impurity_decrease: 0.0
        init: ~
        random_state: 42
        max_features: ~
        verbose: 0
        max_leaf_nodes: ~
        warm_start: False
        validation_fraction: 0.1
        n_iter_no_change: ~
        tol: 0.0001
        ccp_alpha: 0.0
    centralized:
        trainset: experiments/10K_accts/data/preprocessed/centralized/trainset_nodes.csv
        loss: log_loss
        learning_rate: 0.02255690138497708
        criterion: squared_error
        max_depth: 782
    isolated:
        clients:
            c0:
                trainset: experiments/10K_accts/data/preprocessed/clients/c0/trainset_nodes.csv
                loss: exponential
                learning_rate: 0.0010255409356471254
                criterion: squared_error
                max_depth: 577
    search_space:
        loss:
            type: categorical
            values: [log_loss, exponential]
        learning_rate:
            type: float
            low: 0.0001
            high: 0.1
            log: true
        criterion:
            type: categorical
            values: [friedman_mse, squared_error]
        max_depth:
            type: int
            low: 1
            high: 10
